### **2013 Statewise Forest data**

Import all required libraries

In [2]:
import pandas as pd
import numpy as np
import scipy as sc
import math

Import the data_1 file

In [3]:
data_1=pd.read_excel('data_1.xlsx')
data_1.columns

Index(['State/ Uts', 'Geographical Area',
       '2013 Assessment - Very Dense Forest',
       '2013 Assessment - Mod. Dense Forest',
       '2013 Assessment - Open Forest Forest',
       '2013 Assessment - Total Forest Forest', 'Percent of Geographical Area',
       'Change in Forest Cover wrt ISFR 2011', 'Change percent', 'Scrub'],
      dtype='object')

In [4]:
data_1.head()

          State/ Uts Geographical Area  ... Change percent   Scrub
0     Andhra Pradesh          2,75,069  ...          -0.10  10,465
1  Arunachal Pradesh            83,743  ...          -0.11     121
2              Assam            78,438  ...           0.00     182
3              Bihar            94,163  ...           0.47     115
4       Chhattisgarh          1,35,191  ...          -0.04     117

[5 rows x 10 columns]

Percentage of missing values

In [5]:
data_1.isnull().sum()

State/ Uts                               0
Geographical Area                        0
2013 Assessment - Very Dense Forest      0
2013 Assessment - Mod. Dense Forest      0
2013 Assessment - Open Forest Forest     0
2013 Assessment - Total Forest Forest    0
Percent of Geographical Area             0
Change in Forest Cover wrt ISFR 2011     0
Change percent                           0
Scrub                                    0
dtype: int64

No missing Values-0% missing values

## **Checking the data type and converting to desired**

In [6]:
data_1.dtypes

State/ Uts                                object
Geographical Area                         object
2013 Assessment - Very Dense Forest       object
2013 Assessment - Mod. Dense Forest       object
2013 Assessment - Open Forest Forest      object
2013 Assessment - Total Forest Forest     object
Percent of Geographical Area             float64
Change in Forest Cover wrt ISFR 2011     float64
Change percent                           float64
Scrub                                     object
dtype: object

In [7]:
data_1['2013 Assessment - Very Dense Forest']=data_1['2013 Assessment - Very Dense Forest'].str.replace(',','').astype(float)
data_1['Geographical Area']=data_1['Geographical Area'].str.replace(',','').astype(float)
data_1['2013 Assessment - Mod. Dense Forest']=data_1['2013 Assessment - Mod. Dense Forest'].str.replace(',','').astype(float)
data_1['2013 Assessment - Open Forest Forest']=data_1['2013 Assessment - Open Forest Forest'].str.replace(',','').astype(float)
data_1['2013 Assessment - Total Forest Forest']=data_1['2013 Assessment - Total Forest Forest'].str.replace(',','').astype(float)

In [8]:
data_1.dtypes

State/ Uts                                object
Geographical Area                        float64
2013 Assessment - Very Dense Forest      float64
2013 Assessment - Mod. Dense Forest      float64
2013 Assessment - Open Forest Forest     float64
2013 Assessment - Total Forest Forest    float64
Percent of Geographical Area             float64
Change in Forest Cover wrt ISFR 2011     float64
Change percent                           float64
Scrub                                     object
dtype: object

In [9]:
data_1.describe()

       Geographical Area  ...  Change percent
count       3.100000e+01  ...        36.00000
mean        2.120418e+05  ...         0.23250
std         5.798576e+05  ...         0.97966
min         1.483000e+03  ...        -1.65000
25%         2.237800e+04  ...        -0.04250
50%         7.971400e+04  ...         0.00500
75%         1.939065e+05  ...         0.20000
max         3.287263e+06  ...         4.29000

[8 rows x 8 columns]

convert the dataframe to csv

In [10]:
data_1.to_csv('2013.csv')

Change the values of row using at function

```
# DataFrame.at[index_no, 'column']='new_value'
```

In [12]:
data_1.at[28,'State/ Uts']='West Bengal'
data_1.at[14,'State/ Uts']='Madhya Pradesh'
data_1.at[10,'State/ Uts']='Jammu and Kashmir'

## 2013 statewise data in dataframe format

In [13]:
data_1.style.set_caption("2013 Forest covered statewise in india")